// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: internal/output/index.proto

package output

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Posting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        uint32                 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posting) Reset() {
	*x = Posting{}
	mi := &file_internal_output_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posting) ProtoMessage() {}

func (x *Posting) ProtoReflect() protoreflect.Message {
	mi := &file_internal_output_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posting.ProtoReflect.Descriptor instead.
func (*Posting) Descriptor() ([]byte, []int) {
	return file_internal_output_index_proto_rawDescGZIP(), []int{0}
}

func (x *Posting) GetFileId() uint32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *Posting) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PostingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postings      []*Posting             `protobuf:"bytes,1,rep,name=postings,proto3" json:"postings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostingList) Reset() {
	*x = PostingList{}
	mi := &file_internal_output_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostingList) ProtoMessage() {}

func (x *PostingList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_output_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostingList.ProtoReflect.Descriptor instead.
func (*PostingList) Descriptor() ([]byte, []int) {
	return file_internal_output_index_proto_rawDescGZIP(), []int{1}
}

func (x *PostingList) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

type InvertedIndex struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Files         []string                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Index         map[string]*PostingList `protobuf:"bytes,2,rep,name=index,proto3" json:"index,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvertedIndex) Reset() {
	*x = InvertedIndex{}
	mi := &file_internal_output_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvertedIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvertedIndex) ProtoMessage() {}

func (x *InvertedIndex) ProtoReflect() protoreflect.Message {
	mi := &file_internal_output_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvertedIndex.ProtoReflect.Descriptor instead.
func (*InvertedIndex) Descriptor() ([]byte, []int) {
	return file_internal_output_index_proto_rawDescGZIP(), []int{2}
}

func (x *InvertedIndex) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *InvertedIndex) GetIndex() map[string]*PostingList {
	if x != nil {
		return x.Index
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Words         map[string]uint32      `protobuf:"bytes,3,rep,name=words,proto3" json:"words,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_internal_output_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_output_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_internal_output_index_proto_rawDescGZIP(), []int{3}
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FileEntry) GetWords() map[string]uint32 {
	if x != nil {
		return x.Words
	}
	return nil
}

type FileIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileEntry           `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileIndex) Reset() {
	*x = FileIndex{}
	mi := &file_internal_output_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileIndex) ProtoMessage() {}

func (x *FileIndex) ProtoReflect() protoreflect.Message {
	mi := &file_internal_output_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileIndex.ProtoReflect.Descriptor instead.
func (*FileIndex) Descriptor() ([]byte, []int) {
	return file_internal_output_index_proto_rawDescGZIP(), []int{4}
}

func (x *FileIndex) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_internal_output_index_proto protoreflect.FileDescriptor

const file_internal_output_index_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/output/index.proto\x12\x06output\"8\n" +
	"\aPosting\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\rR\x06fileId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\":\n" +
	"\vPostingList\x12+\n" +
	"\bpostings\x18\x01 \x03(\v2\x0f.output.PostingR\bpostings\"\xac\x01\n" +
	"\rInvertedIndex\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\x126\n" +
	"\x05index\x18\x02 \x03(\v2 .output.InvertedIndex.IndexEntryR\x05index\x1aM\n" +
	"\n" +
	"IndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.output.PostingListR\x05value:\x028\x01\"\xa3\x01\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x122\n" +
	"\x05words\x18\x03 \x03(\v2\x1c.output.FileEntry.WordsEntryR\x05words\x1a8\n" +
	"\n" +
	"WordsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"4\n" +
	"\tFileIndex\x12'\n" +
	"\x05files\x18\x01 \x03(\v2\x11.output.FileEntryR\x05filesB\"Z mycontext/internal/output;outputb\x06proto3"

var (
	file_internal_output_index_proto_rawDescOnce sync.Once
	file_internal_output_index_proto_rawDescData []byte
)

func file_internal_output_index_proto_rawDescGZIP() []byte {
	file_internal_output_index_proto_rawDescOnce.Do(func() {
		file_internal_output_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_output_index_proto_rawDesc), len(file_internal_output_index_proto_rawDesc)))
	})
	return file_internal_output_index_proto_rawDescData
}

var file_internal_output_index_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_output_index_proto_goTypes = []any{
	(*Posting)(nil),       // 0: output.Posting
	(*PostingList)(nil),   // 1: output.PostingList
	(*InvertedIndex)(nil), // 2: output.InvertedIndex
	(*FileEntry)(nil),     // 3: output.FileEntry
	(*FileIndex)(nil),     // 4: output.FileIndex
	nil,                   // 5: output.InvertedIndex.IndexEntry
	nil,                   // 6: output.FileEntry.WordsEntry
}
var file_internal_output_index_proto_depIdxs = []int32{
	0, // 0: output.PostingList.postings:type_name -> output.Posting
	5, // 1: output.InvertedIndex.index:type_name -> output.InvertedIndex.IndexEntry
	6, // 2: output.FileEntry.words:type_name -> output.FileEntry.WordsEntry
	3, // 3: output.FileIndex.files:type_name -> output.FileEntry
	1, // 4: output.InvertedIndex.IndexEntry.value:type_name -> output.PostingList
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_output_index_proto_init() }
func file_internal_output_index_proto_init() {
	if File_internal_output_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_output_index_proto_rawDesc), len(file_internal_output_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_output_index_proto_goTypes,
		DependencyIndexes: file_internal_output_index_proto_depIdxs,
		MessageInfos:      file_internal_output_index_proto_msgTypes,
	}.Build()
	File_internal_output_index_proto = out.File
	file_internal_output_index_proto_goTypes = nil
	file_internal_output_index_proto_depIdxs = nil
}
